from pathlib import Path
import re
import subprocess
import sys
from textwrap import dedent

from tqdm import tqdm

SQUIRREL_BIN = Path('squirrel/bin/sq')
SCRIPTS = Path('resources/scripts')
OUTPUTS = Path('squirrel_lang/src/runtime/snapshots')
OUTPUTS.mkdir(parents=True, exist_ok=True)
MACRO_FILE = Path('squirrel_lang/src/test_macro.rs')

class Module:
    def __init__(self):
        self.scripts = []
        self.submodules = {}

    def get_submod(self, name):
        if name not in self.submodules:
            self.submodules[name] = Module()
        return self.submodules[name]

    def print_mod(self, mod_name, hier, handle, indent):
        print('#[rustfmt::skip]', file=handle)
        print(f'{pad(indent)}mod {mod_name} {{', file=handle)
        print(f'{pad(indent+1)}use super::$func;', file=handle)
        if len(self.scripts) > 0:
            print(f'{pad(indent+1)}use crate::test_macro::data::{hier}::*;', file=handle)
        for script in self.scripts:
            script_name = script.split('.', 1)[0]
            script_upper = script_name.upper()
            print(f'{pad(indent+1)}#[test]', file=handle)
            print(f'{pad(indent+1)}fn test_{script_name}() {{', file=handle)
            print(f'{pad(indent+2)}$func({script_upper}_PATH, {script_upper}_CONTENTS);', file=handle)
            print(f'{pad(indent+1)}}}', file=handle)

        for mod_name, mod in self.submodules.items():
            mod.print_mod(mod_name, f'{hier}::{mod_name}', handle, indent+1)

        print(f'{pad(indent)}}}', file=handle)

    def print_constants(self, mod_name, hier, handle, indent):
        print(f'{pad(indent)}pub mod {mod_name} {{', file=handle)
        for script in self.scripts:
            script_name = script.split('.', 1)[0]
            script_upper = script_name.upper()
            print(f'{pad(indent+1)}pub const {script_upper}_PATH: &str = "{hier}/{script}";', file=handle)
            print(f'{pad(indent+1)}pub const {script_upper}_CONTENTS: &str = include_str!("../../resources/scripts/{hier}/{script}");', file=handle)

        for mod_name, mod in self.submodules.items():
            mod.print_constants(mod_name, hier / mod_name, handle, indent+1)

        print(f'{pad(indent)}}}', file=handle)

root_mod = Module()

def register_script(script):
    hier = script.relative_to(SCRIPTS).parent.parts
    module = root_mod
    output_name_components = []
    for part in hier:
        module = module.get_submod(part)
        output_name_components.append(part)
    module.scripts.append(script.name)
    output_name_components.append(script.name)
    output = OUTPUTS / f'squirrel_lang__runtime__walker__tests__walker-{"-".join(output_name_components)}.snap'
    script_ident = script.relative_to(SCRIPTS)
    print(script_ident)
    with output.open('w') as handle:
        handle.write(dedent(f"""\
            ---
            source: squirrel_lang/src/runtime/walker.rs
            expression: Walker test for {script_ident} (Generated by sq_expect.py)
            ---
            """))
        handle.flush()
        res = subprocess.run([SQUIRREL_BIN, str(script)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if len(res.stderr) > 0:
            print("Error:")
            print(res.stderr.decode())
        output = res.stdout.decode()
        output = re.sub(r"\(([a-z]+) : 0x(?:0x)?[0-9a-f]+\)", r"(\1 : 0x<memory>)", output)
        handle.write(output)

for dirpath, dirnames, filenames in SCRIPTS.walk(follow_symlinks=True):
    for file in filenames:
        if file.endswith('.nut'):
            register_script(dirpath / file)

def pad(amt):
    return ' ' * amt * 4

with open(MACRO_FILE, 'wt') as handle:
    print('#[macro_export]', file=handle)
    print('macro_rules! test_foreach {', file=handle)
    print('    ($func:tt) => {', file=handle)
    assert len(root_mod.scripts) == 0
    for name, sub_mod in root_mod.submodules.items():
        sub_mod.print_mod(name, Path(name), handle, 2)
    print('    };', file=handle)
    print('}', file=handle)
    print('#[rustfmt::skip]', file=handle)
    print('pub mod data {', file=handle)
    for name, sub_mod in root_mod.submodules.items():
        sub_mod.print_constants(name, Path(name), handle, 1)
    print('}', file=handle)